### ISSUE TITLE
Broken uploads list

### ISSUE THREAD

**Issue by codyzu** [web3-storage/w3ui#118]
For the last 2 days, the react uploads list has been returning undefined for the `dataCid` and `carCids`. Some initial debugging of the network requests looks like the API is not returning the CIDs... has something recently changed?

Thanks for all of your hard work!

For reference, my code is here: http://github.com/codyzu/ipfs-drive

**Comment by jchris** [comment]
I had the same experience. There was a service format change, so you have to update all the modules. Any existing uploads will not list on the new modules until we do a backend data migration. Apologies. Part of getting out of beta will mean moving to a rolling upgrade policy so this can't happen again

**Comment by codyzu** [comment]
Great! Thanks... I understand how it goes when APIs are in beta. This is a fast-moving project, so totally understandable.

I did update all of the modules this morning and new uploads are still not listed (maybe because these files were already uploaded when previously logged in???).

Thanks for all of your help!

**Comment by codyzu** [comment]
As per @alanshaw 's help in person at IPFS camp 🙌 , I also needed to delete `node_modules` and lock files then re-install 🤦  ✨ 

That fixed it. I'm going to close this. Thanks
