### ISSUE TITLE
Correct Return types of providers

### ISSUE THREAD

**Issue by Codigo-Fuentes** [web3-storage/w3ui#122]
Fix here: https://github.com/web3-storage/w3ui/compare/main...fix/updateReturnTypes

<img width="1680" alt="type-errors" src="https://user-images.githubusercontent.com/43380153/201142711-b51805c4-db7b-4d70-b199-dc389a3764ef.png">

**Comment by travis** [comment]
sorry for the delay - just verified this is fixed in the latest packages!
