### ISSUE TITLE
update w3console theme to align with that of w3ui

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/w3ui#134]
With these updates, we are hoping to target users who want to add uploads to their website (e.g., by dropping a widget in to their site)

Work will go into the new w3console repo that @travis is assembling now.  (location currently unknown)

- [ ] Make w3ui components default theme look like w3ui website (see below)
- [ ] Rebuild w3console in latest version of w3ui, refine style to match w3ui default style
- [ ] Use lessons learned in w3console layout to inform how w3ui monolithic components will look

<img width="235" alt="example" src="https://user-images.githubusercontent.com/5795335/205091332-3a62b67f-0a23-4ab6-9e4c-638c2fc219df.png">

Notes from @jchris 
I like how the color shifts across the steps, it does a good job of saying step 1, 2, 3

maybe the drop target uploader and the list aren't on the screen on the same time in the monolithic component? like a link to the uploads list from the red screen, that minimizes (but doesn't hide) the drop target, and shows the upload list. color can shift to purple if that's not too extra.

This ticket relates to work found here: https://github.com/web3-storage/w3ui/issues/120

**Comment by jchris** [comment]
a clearer description of the work phases on this theme style project might be:

1. Make w3ui components default theme look like w3ui website
2. Rebuild w3console in latest version of w3ui, refine style to match w3ui default style
3. Use lessons learned in w3console layout to inform how w3ui monolithic components will look

**Comment by cmunns** [comment]
The gradients themselves don't lend themselves well to an integrated set of components, nor should we be that opinionated about their display even if for w3console. Here is a video of a reworked multi-uploader that is more user friendly with styles ( controlled via css custom properties for very easy user modifications of this styled version ). It's a start...

https://user-images.githubusercontent.com/1189523/205180728-4d2f947d-9c36-4604-a765-326ea37dad6d.mov
