### ISSUE TITLE
layout and design work for w3console

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/w3ui#142]
Before this work can start, the following must be complete:

- [x] https://github.com/web3-storage/w3ui/issues/120
- [x] user flows @jchris which isn't yet ticketed but referenced here: https://github.com/web3-storage/w3protocol/issues/220

**Comment by jchris** [comment]
![Image](https://user-images.githubusercontent.com/253/206316066-3176c722-7b25-4c2f-a162-3769c9a56033.png)


From meeting with @dchoi27 -- would like to connect with @Gozala on it also

**Comment by jchris** [comment]
<img width="898" alt="Screen Shot 2022-12-14 at 9 35 51 AM" src="https://user-images.githubusercontent.com/253/207930907-09e1c4f9-88e4-4495-923f-904f3955ecfe.png">

Here is an updated view, and [here are w3console principles that might help](https://www.notion.so/w3console-in-dotStorage-238012eb375647b2a5b305e1572de658)
