### ISSUE TITLE
add a `react-ui` package with "customizable" components

### ISSUE THREAD

**Issue by travis** [web3-storage/w3ui#147]
Per https://github.com/web3-storage/w3ui/issues/120#issuecomment-1334293070 introduce a new package called `react-ui` that contains "customizable" components. 

This work has started in https://github.com/web3-storage/w3ui/pull/136 and @cmunns has a prototype for how the CSS-variable-based customization could work in https://github.com/web3-storage/w3ui/pull/140

Components in this library will utilize the "headless" components from https://github.com/web3-storage/w3ui/issues/145. Developers should be able to use them out of the box, and we should document the CSS variables they can use to customize the look and feel of the components when used in third party apps.

**Comment by jchris** [comment]
This will have an all in one flow that includes login
<img width="1506" alt="Screen Shot 2022-12-06 at 4 52 42 PM" src="https://user-images.githubusercontent.com/253/206061307-c36537b3-773d-4e26-8b5d-c26c2fc81714.png">

**Comment by jchris** [comment]
app owned space can bypass login
