### ISSUE TITLE
codesandbox examples are not compiling

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/w3ui#160]
I believe because we now have `node_modules` that include private class properties.

**Comment by yusefnapora** [comment]
Just dropping a link to a failing example: https://codesandbox.io/s/github/web3-storage/w3ui/tree/main/examples/react/sign-up-in

Also found this minimal repro case via google: https://codesandbox.io/s/doyiu which suggests codesandbox just doesn't support private class properties.

Seems like maybe if we tweak the rollup config we could have babel transform them for us in builds... right now it's [excluding everything in node_modules](https://github.com/web3-storage/w3ui/blob/main/rollup.config.ts#L32), but maybe we could whitelist the problematic deps.

**Comment by yusefnapora** [comment]
Opened an issue with codesandbox to see if they can flip a switch on their end: https://github.com/codesandbox/codesandbox-client/issues/7244
