### ISSUE TITLE
proposal: React useUploadsList hook should automatically load one page of results

### ISSUE THREAD

**Issue by travis** [web3-storage/w3ui#200]
while fixing the react uploads list example (https://github.com/web3-storage/w3ui/pull/195) I noticed that the useUploadsList hook doesn't automatically load the first page of results - I think this is a bug but figured I'd double check before changing the current behavior.

**Comment by travis** [comment]
@jchris @alanshaw @yusefnapora would love your thoughts in particular on this one

**Comment by jchris** [comment]
I think that's a bug, at least in my apps it's loaded automatically

**Comment by travis** [comment]
ok great - I'll take another look at this now that all the in progress pnpm work has landed

**Comment by travis** [comment]
fixed in #254, merged with #236
