### ISSUE TITLE
Missing Space

### ISSUE THREAD

**Issue by paschal533** [web3-storage/w3ui#205]
Hi, I'm getting this error `Unhandled Runtime Error: missing space` while trying to upload a file to ipfs using w3ui.

Here is the code I wrote for it

```
import React, { useState } from 'react'
import { useUploader } from '@w3ui/react-uploader'

export default function Component () {
  const [, uploader] = useUploader()
  const [file, setFile] = useState(null)
  const [dataCid, setDataCid] = useState('')

  const handleUploadSubmit = async e => {
    e.preventDefault()
    const cid = await uploader.uploadFile(file)
    setDataCid(cid)
  }

  if (dataCid) {
    return (
      <div>
        <h1>Done!</h1>
        <p>{dataCid.toString()}</p>
        <p><a href={`https://${dataCid}.ipfs.w3s.link`}>View {file.name} on IPFS Gateway.</a></p>
      </div>
    )
  }

  return (
    <form onSubmit={handleUploadSubmit}>
      <div>
        <label htmlFor='file'>File:</label>
        <input id='file' type='file' onChange={e => setFile(e.target.files[0])} required />
      </div>
      <button type='submit'>Upload</button>
    </form>
  )
}
```

App.jsx file

```
import { KeyringProvider, useKeyring } from '@w3ui/react-keyring'
import { UploaderProvider } from '@w3ui/react-uploader'

const MyApp = ({ Component, pageProps }: AppProps) => {
  return (
     <KeyringProvider>
          <UploaderProvider>
             <AgentLoader>
               <Component {...pageProps} />
             </AgentLoader>
          </UploaderProvider>
      </KeyringProvider>
  )
}

function AgentLoader ({ children  } : any) {
  const [, { loadAgent }] = useKeyring()
  // eslint-disable-next-line
  useEffect(() => { loadAgent() }, []) // load agent - once.
  return children
}

export default MyApp;
```

**Comment by travis** [comment]
thanks @paschal533! I'll take a look at this tomorrow

**Comment by travis** [comment]
Ah - you need to wrap `Component` in an `Authenticator` - the example in https://github.com/web3-storage/w3ui/blob/main/examples/react/file-upload/src/ContentPage.jsx does this by wrapping the `ContentPage` component using `withIdentity` - you'll probably want to copy the `Authenticator` component wholesale from https://github.com/web3-storage/w3ui/blob/main/examples/react/file-upload/src/components/Authenticator.jsx and use it in your example.

We're working to publish a reusable version of `Authenticator` but for now copy-paste is your best bet. I'm going to close this issue but please re-open if this doesn't fix the error you're seeing!

**Comment by paschal533** [comment]
Okay, I did that but I'm getting this error now

```
Error: Voucher claim failed at hl.registerSpace 

name : "Unauthorized"

```

**Comment by travis** [comment]
hm, interesting - @paschal533 could you elaborate on where you're seeing this error? would it be possible to push your code to a public repository to make it easy for me to reproduce and debug?

**Comment by travis** [comment]
closing as it's been a while - please reopen if this is still a problem
