### ISSUE TITLE
add integration tests

### ISSUE THREAD

**Issue by travis** [web3-storage/w3ui#222]
Chatted with @olizilla and @yusefnapora this morning and we are inclined to do browser testing with some third party service that makes it easy and low maintenance. Need to investigate the state of the art for this kind of testing.

**Comment by olizilla** [comment]
There's "the test framework" and "the cloud test service", and some frameworks can be run by multiple services

| test framework | cloud service | feels like |
|----------------|---------------|----------|
| cypress             | [cypress cloud](https://docs.cypress.io/guides/cloud/introduction#Benefits), [browserstack](https://www.browserstack.com/automate/cypress), lambdatest | mocha + chai |
| playwright-test | [lambdaTest](https://www.lambdatest.com/playwright-testing) | ava + expect (but you can [drive `playwight` from any test framework](https://playwright.dev/docs/test-runners)

**Comment by olizilla** [comment]
Added integration tests using @playwright/test to drive the browser orchestration in #242 as the first part of this. I think the scope of this issue should be "have integrations tests we are happy with". We can adopt a testing service if we find friction or features that we need.
