### ISSUE TITLE
codesandbox examples build but error when run

### ISSUE THREAD

**Issue by olizilla** [web3-storage/w3ui#237]
We've got codesandox-ci running on our PRs and it seems to build fine, but trying to run the examples fails with an error, and no debugging info.

of note:
- it only supports building via `npm` which is probably the cause of our examples not being runnable.
- codesandbox only supports up to node v16.

It may not be possible to make our build work in `npm` now we rely on features of `pnpm`, so we may have to disable `pnpm` ci, as it's a confusing signal for us to get green check on PRs even when the examples fail to run.

example build: https://ci.codesandbox.io/status/web3-storage/w3ui/pr/220
example sandbox: https://codesandbox.io/s/w3ui-example-react-sign-up-in-z6obt1

**Comment by travis** [comment]
oh dang :-/ I'm on board with dropping codesandbox - I remember poking around at it before the break and it seemed like the lack of support for `pnpm` and node 18 were symptomatic of a general lack of updates/support for it, so maybe time to move on? 

it would still be nice to have the examples available in something like codesandbox, are there alternatives out there?
