### ISSUE TITLE
Unhandled Runtime Error Error: failed to register

### ISSUE THREAD

**Issue by hassanuahmad** [web3-storage/w3ui#257]
I cloned the sign in / up repo but when I run it on my local machine and enter the email, it gives an error **Unhandled Runtime Error Error: failed to register**

This is my code for app.tsx

```js
import "../styles/globals.css";
import type { AppProps } from "next/app";
import Layout from "../components/layout";
import { KeyringProvider } from "@w3ui/react-keyring";

export default function App({ Component, pageProps }: AppProps) {
    return (
        <KeyringProvider>
            <Layout>
                <Component {...pageProps} />
            </Layout>
        </KeyringProvider>
    );
}
```

and this is my code for the actual auth

```js
import React, { useEffect, useState } from "react";
import { useKeyring } from "@w3ui/react-keyring";

export default function AuthenticationPage() {
    const [
        { space },
        {
            loadAgent,
            unloadAgent,
            createSpace,
            registerSpace,
            cancelRegisterSpace,
        },
    ] = useKeyring();
    const [email, setEmail] = useState("");
    const [submitted, setSubmitted] = useState(false);

    useEffect(() => {
        loadAgent();
    }, []); // load the agent - once.

    if (space?.registered()) {
        return (
            <div>
                <h1>Welcome!</h1>
                <p>You are logged in!!</p>
                <form
                    onSubmit={(e) => {
                        e.preventDefault();
                        unloadAgent();
                    }}
                >
                    <button type="submit">Sign Out</button>
                </form>
            </div>
        );
    }

    if (submitted) {
        return (
            <div>
                <h1>Verify your email address!</h1>
                <p>
                    Click the link in the email we sent to {email} to sign in.
                </p>
                <form
                    onSubmit={(e) => {
                        e.preventDefault();
                        cancelRegisterSpace();
                    }}
                >
                    <button type="submit">Cancel</button>
                </form>
            </div>
        );
    }

    const handleRegisterSubmit = async (e) => {
        e.preventDefault();
        setSubmitted(true);
        try {
            await createSpace();
            console.log("####EMAIL", email);
            await registerSpace(email);
        } catch (err) {
            throw new Error("failed to register", { cause: err });
        } finally {
            setSubmitted(false);
        }
    };

    return (
        <form onSubmit={handleRegisterSubmit}>
            <div>
                <label htmlFor="email">Email address:</label>
                <input
                    id="email"
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    required
                />
            </div>
            <button type="submit" disabled={submitted}>
                Register
            </button>
        </form>
    );
}
```

Exactly using what was given but when I enter the email, it sends a verification link to the email and when I click on it, it gives an error that it cant register the space. not really sure what the issue but any help would be appreciated. 

![Screenshot 2023-01-14 at 6 22 15 PM](https://user-images.githubusercontent.com/72142523/212501444-4a7d42ff-433f-41f3-ace4-c8487ee878fe.png)

**Comment by travis** [comment]
hi @hassanuahmad ! thanks for the bug report - are you able to push your code to a public repository so I can try to debug what's going on here? what you're doing looks right to me so I'd like to dig a bit deeper.

**Comment by hassanuahmad** [comment]
I literally just cloned this repo and tried it! Its giving the same error.

https://github.com/web3-storage/w3ui/tree/main/examples/react/sign-up-in

**Comment by travis** [comment]
hm, odd, I just pulled the latest from `main` and it seems to be working - we did merge a few fixes in the past few days, could you try pulling the latest and try this again?

**Comment by hassanuahmad** [comment]
I tried again and also screen recorded it so here is a link to it

https://youtu.be/pQVZ3g8P7a8

**Comment by travis** [comment]
Thank you! This is super helpful. One question - could you take a look at the network tab after hitting "Register"? It looks like there's an error on the network/service side somewhere between when you hit "Register" and when you came back to the tab after hitting "Verify email address"  - it would be super helpful to know what the request/response looked like there. Also worth looking at what's going on with websockets during that flow. 

Apologies for this instability, will do our best to figure out what's going on and resolve asap!

**Comment by hassanuahmad** [comment]
So this is what the network tab shows for me
![image](https://user-images.githubusercontent.com/72142523/213316786-7ef5ce11-50eb-4e78-9ab8-1f82dcd5a7e9.png)

**Comment by tennox** [comment]
I encountered a problem too, I guess it's the same?
```
TypeError: Cannot read properties of undefined (reading 'identity')
    at _$f.registerSpace (agent.js:492:52)
    at async registerSpace (Keyring.ts:134:25)
    at async HTMLFormElement.handleAuthorizeSubmit (StorageControls.tsx:107:5)
```

I also reproduced it in the [solid example on main branch](https://github.com/web3-storage/w3ui/blob/main/examples/solid/file-upload/src/components/Authenticator.jsx#L13) with a fresh email address:
```
Uncaught (in promise) Error: failed to register
    at HTMLFormElement.handleRegisterSubmit (Authenticator.jsx:17:13)
handleRegisterSubmit @ Authenticator.jsx:17
```

**Comment by hassanuahmad** [comment]
I think this only happens on Safari and not on any Chromium browser!

**Comment by tennox** [comment]
No, we're on chromium.

We've kind of worked around it by trying to register again after some time. `registerSpace` - but it's far from nice.
Will have to investigate further.

Jun 16, 2023 22:35:38 Hassan U Ahmad ***@***.***>:
