### ISSUE TITLE
Showing upload progress

### ISSUE THREAD

**Issue by olizilla** [web3-storage/w3ui#378]
We want to show a progress bar to inform the user of what is happening during an upload. At a minimum we want to show how much of the data has been send to w3, e.g.

<img width="290" alt="Screenshot 2023-02-06 at 10 30 01" src="https://user-images.githubusercontent.com/58871/216948892-10623aa6-cad2-4321-ae71-4e6721b2d09f.png">

But there are some hurdles! 
- The `upload-client` library doesn't expose an upload progress callback
- under the hood [we use `fetch`](https://github.com/web3-storage/w3protocol/blob/4d72ba3a1ce2564cda13c62137967613b18334a7/packages/upload-client/src/store.js#L73-L79) which doesn't provide a [mechanism to report upload progress.](https://stackoverflow.com/a/35747208/6490163)

Some options

1. Update `upload-client` to use `XMLHttpRequest` where available, which provides a [`progress` event](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/progress_event)
2. Update `upload-client` to use fetch with a `ReadableStream` as the Request body. We wrap the body in a custom stream that just tracks number of bytes that pass through it, and use this as a proxy for bytes actually sent. This is supported in by about [60% of current browsers](https://caniuse.com/mdn-api_request_request_request_body_readablestream), notably Chrome & Edge, but not Firefox or Safari. There are caveats too, e.g. http2 connection required, [outlined here](https://developer.chrome.com/articles/fetch-streaming-requests/)

Part of https://github.com/web3-storage/w3ui/issues/134

**Comment by olizilla** [comment]
aws suggest using xhr to show upload progress in browsers – https://github.com/aws/aws-sdk-js-v3/blob/main/packages/xhr-http-handler/README.md

fetch with a ReadableStream body requires `duplex: half` to be set – https://github.com/bluesky-social/atproto/pull/470

**Comment by heyjay44** [comment]
This will be put on hold. Interim solution can be found in this ticket: https://github.com/web3-storage/w3protocol/issues/655
