### ISSUE TITLE
useKeyring is puzzling me

### ISSUE THREAD

**Issue by jchris** [web3-storage/w3ui#396]
I must have missed something copying from w3console, but my proofs are coming back as an empty array.

https://github.com/jchris/fireproof/blob/b92622e4bdd4dad431958b92b36104e054f1692b/examples/todomvc/src/App.tsx#L153

**Comment by jchris** [comment]
It turns out the fix was I had to muck with the store capability on the way in https://github.com/jchris/fireproof/commit/7e49dfb8263f92fc3cab2dfe4a662403582d918a#diff-054c00d5326bfafe659023744ea7e47a8f681520301fde53281d8275895daf5cR152

**Comment by travis** [comment]
I believe this should be fixed - we probably weren't requesting the required capabilities in the lower level libraries - please reopen if it's still a problem!
