### ISSUE TITLE
Include warnings for permanent and public data in deployed web apps

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/w3ui#401]
Similar to https://github.com/web3-storage/w3cli/commit/84a9fd56c287939c4127c9b8e03e2b661a751d79,

let's include the following warnings in the uploader of the deployed w3consoles for the web3.storage and NFT.Storage w3up beta web apps:

> ⚠️❗ __Public Data__ 🌎: All data uploaded to web3.storage is available to anyone who requests it using the correct CID. Do not store any private or sensitive information in an unencrypted form using web3.storage.
> ⚠️❗ __Permanent Data__ ♾️: Deleting files from the web3.storage site’s Files page will remove them from the file listing for your account, but that doesn’t prevent nodes on the decentralized storage network from retaining copies of the data indefinitely. Do not use web3.storage for data that may need to be permanently deleted in the future.

These are already in the ToS, but we want to emphasize this

**Comment by travis** [comment]
closed by #502
