### ISSUE TITLE
failed to register     handleRegisterSubmit Authenticator.jsx:17 Caused by: Error: Voucher claim failed

### ISSUE THREAD

**Issue by tennox** [web3-storage/w3ui#545]
Encountered this locally and could reproduce in official [codesandbox example](https://codesandbox.io/p/sandbox/w3ui-example-solid-file-upload-forked-9z8hqk):
```
Error: failed to register
    handleRegisterSubmit Authenticator.jsx:17
Caused by: Error: Voucher claim failed
    registerSpace agent.js:472
    registerSpace Keyring.ts:131
    handleRegisterSubmit Authenticator.jsx:15
```

Note that the react example works fine, while solidJS does not.

The error I found to be returned from POST to `up.web3.storage` is:
```
{
    "error": {
        "name": "HandlerNotFound",
        "error": true,
        "stack": "HandlerNotFound: service does not implement {can: \"voucher/claim\"} handler\n    at invoke (/node_modules/@ucanto/server/src/server.js:134:16)\n    at <anonymous> (/node_modules/@ucanto/server/src/server.js:95:47)\n    at Array.map (<anonymous>)\n    at execute (/node_modules/@ucanto/server/src/server.js:95:38)\n    at ucanInvocationRouter (/upload-api/functions/ucan-invocation-router.js:195:33)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at Runtime.handler (/node_modules/src/awslambda.ts:308:1)",
        "message": "service does not implement {can: \"voucher/claim\"} handler",
        "capability": {
            "can": "voucher/claim",
            "with": "did:key:z6MkfkouXRXPDZDDHV7esYg3UHjo93zZ6gNVYUw2Lat5kXGH"
        }
    }
}
```

**Comment by tennox** [comment]
I [updated the codesandbox ](https://codesandbox.io/p/sandbox/w3ui-example-solid-file-upload-forked-9z8hqk?file=/package.json:22,2)to the latest master commit https://github.com/web3-storage/w3ui/commit/e2fe0dd0c8824b4b3ce70e1c3ddb47c67205bb43 - but still get the error (visible in console during registration, after email confirmation is done):

![image](https://github.com/web3-storage/w3ui/assets/2084639/d2f6e02e-d794-40e4-8916-4487f00bc02c)

**Comment by travis** [comment]
thanks for the bug report! I've sorted this out - @web3-storage/access-client was mis-built. #548 and a subsequent PR to bump other package numbers should sort this out.

in the meantime I believe you can call `registerSpace` with the `provider` option set to `did:web:staging.web3.storage` to trigger the correct codepath, something like:

```
registerSpace(email, {provider: 'did:web:staging.web3.storage'})
```

**Comment by gotjoshua** [comment]
{name: 'InvalidProvider', message: 'Invalid provider: did:web:staging.web3.storage'}

![image](https://github.com/web3-storage/w3ui/assets/8686454/ae65e953-9c4f-4896-b282-6c33261458fe)

**Comment by gotjoshua** [comment]
got it.  
from:  
https://github.com/web3-storage/w3up/tree/main/packages/w3up-client#creating-and-registering-spaces

`{ provider: 'did:web:web3.storage' }`

we were using 
`{ provider: 'did:web:up.web3.storage' }`
